name: "Lego HA"
description: >-
  Free Dynamic DNS (DynDNS or DDNS) service with Let's Encrypt support and wildcard certificates
version: "1.0.0"
slug: "legoha"
url: https://github.com/hakmo/home-assistant-addons/tree/main/legoha
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
init: false
# image: homeassistant/{arch}-addon-legoagh
map:
  - ssl:rw
options:
  domains:
    - null
  email: null
  provider: duckdns
  token: null
  lets_encrypt:
    accept_terms: false
    algo: ec384
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
schema:
  domains:
    - match(.+\.duckdns\.org)
  email: str
  provider: list(cloudflare|godaddy|digitalocean|duckdns)
  token: str
  secret: str?
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa2048|rsa3072|rsa4096|rsa8192|ec256|ec384)
    certfile: str
    keyfile: str
  seconds: int
  ipv4: str?
  ipv6: str?
startup: services