---
version: 1.0.0
slug: legoago
name: legoagh
description: >-
  Free Dynamic DNS (DynDNS or DDNS) service with Let's Encrypt support and wildcard certificates
url: https://github.com/hakmo/home-assistant-addons/tree/main/legoagh
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
hassio_api: true
init: false
map:
  - ssl:rw
options:
  domains:
    - null
  email: null
  provider: duckdns
  token: null
  secret: null
  aliases: []
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
  seconds: 300
schema:
  domains:
    - match(.+\.duckdns\.org)
  email: str
  provider: list(cloudflare|godaddy|digitalocean|duckdns)
  token: str
  secret: str
  aliases:
    - alias: str
      domain: str
  lets_encrypt:
    accept_terms: bool
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
  seconds: int
  ipv4: str?
  ipv6: str?
startup: services
